"""" Visual configurations
set tabstop=4
set softtabstop=4 expandtab
set autoindent
syntax on
set t_Co=256
colorscheme pablo
set number
set relativenumber
set ruler
set showcmd
set nowrap
set colorcolumn=72
hi ColorColumn ctermbg=darkgrey guibg=darkgrey

"""" Usefull configurations
set foldmethod=marker
set foldmarker={{,}}

"""" Search configurations
set incsearch
set hlsearch
set ignorecase

"""" Mutt
au BufRead ~/.tmp/mutt-* set tw=72

"""" Python configurations
set shiftwidth=4
set smarttab
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class,with
autocmd BufWritePre *.py normal m`:%s/\s\+$//e``

"""" Makefile configuration
autocmd FileType make set noexpandtab softtabstop=0 shiftwidth=8
